apps:
  - script: ./server/index.js
    name: 'myapp'
    exec_mode: 'cluster'
    instances: 0
    log_date_format: 'YYYY-MM-DD HH:mm Z'
    instance_var: 'MYAPP'
    env_production:
      PORT: 3000
      NODE_ENV: production
